branches:
  only:
  - master
install:
- npm install
script:
- npm run build
deploy:
  provider: firebase
    secure: P98yzYHxklIM56M0M3suR+c8ACP+nAW50mldWCyh9uGNArpWK9FXk3fZ/ovvdzRXYGWgpqAQ4jTuXuaOGhF8+ALI70kaqTZThOFCDarOzKP53nA5aSrw9iCeHIm8rTAI01JavYha6dfwmiiTaUjCMPhoBFw7tLHCucnLujtS6ZLB6psv/cN5APvYpQKSMBT5x1q7tQbUtOu1Npg6DnYuGHfoVgH9SSlIRDhiE9+Jy4wOZxcSUfSM0VSKvZD0X0V48zT68tDYhNq3Pra9p6vdFELwpDL52QhwGw1965GFEd1YOACSQbT8ehYAFg8JW8UVvmXpp1c3sxV9WcC4MHqbix/o7vCDiDuYkr2jRbsHcyE8guHPllR/LgTKD6K9sh3Yde12a1Z+hgRSsIfBbbwnVtoXM+U7v8qazxSWvyHB1tbmNcLUAycn3/hwIOSaob6N/EaoPl5QyiLR69JD34z8L7otqSJoQvpKY+fBEUxZCTl/L1L0lrl/rRXAoI1t1o/rNS2TMxvOFrMv+trPvu0dckOf3rvdmz4gsRO2YZ2JmzRnOEG7u+j59Cg4V8wI0wWbvnGr6PHfEWBSmH+HlPNXBh6OeWuWumW6Cvpjq/DCfTpQp5a2BqOUpW5s503LMU00D1bkcCVDHs9iiMbrEKnIdY75wil6Y6P0PVHf1lUHwDc=
  skip_cleanup: true
  project: biblioshare-s1
env:
  global:
    secure: P98yzYHxklIM56M0M3suR+c8ACP+nAW50mldWCyh9uGNArpWK9FXk3fZ/ovvdzRXYGWgpqAQ4jTuXuaOGhF8+ALI70kaqTZThOFCDarOzKP53nA5aSrw9iCeHIm8rTAI01JavYha6dfwmiiTaUjCMPhoBFw7tLHCucnLujtS6ZLB6psv/cN5APvYpQKSMBT5x1q7tQbUtOu1Npg6DnYuGHfoVgH9SSlIRDhiE9+Jy4wOZxcSUfSM0VSKvZD0X0V48zT68tDYhNq3Pra9p6vdFELwpDL52QhwGw1965GFEd1YOACSQbT8ehYAFg8JW8UVvmXpp1c3sxV9WcC4MHqbix/o7vCDiDuYkr2jRbsHcyE8guHPllR/LgTKD6K9sh3Yde12a1Z+hgRSsIfBbbwnVtoXM+U7v8qazxSWvyHB1tbmNcLUAycn3/hwIOSaob6N/EaoPl5QyiLR69JD34z8L7otqSJoQvpKY+fBEUxZCTl/L1L0lrl/rRXAoI1t1o/rNS2TMxvOFrMv+trPvu0dckOf3rvdmz4gsRO2YZ2JmzRnOEG7u+j59Cg4V8wI0wWbvnGr6PHfEWBSmH+HlPNXBh6OeWuWumW6Cvpjq/DCfTpQp5a2BqOUpW5s503LMU00D1bkcCVDHs9iiMbrEKnIdY75wil6Y6P0PVHf1lUHwDc=
