export const spainCities = [
    { title: 'A Coruña'},
    { title: 'Álava'},
    { title: 'Albacete'},
    { title: 'Alicante'},
    { title: 'Almería'},
    { title: 'Asturias'},
    { title: 'Ávila'},
    { title: 'Badajoz'},
    { title: 'Baleares'},
    { title: 'Barcelona'},
    { title: 'Burgos'},
    { title: 'Cáceres'},
    { title: 'Cádiz'},
    { title: 'Cantabria'},
    { title: 'Castellón'},
    { title: 'Ciudad Real'},
    { title: 'Córdoba'},
    { title: 'Cuenca'},
    { title: 'Girona'},
    { title: 'Granada'},
    { title: 'Guadalajara'},
    { title: 'Gipuzkoa'},
    { title: 'Huelva'},
    { title: 'Huesca'},
    { title: 'Jaén'},
    { title: 'La Rioja'},
    { title: 'Las Palmas'},
    { title: 'León'},
    { title: 'Lérida'},
    { title: 'Lugo'},
    { title: 'Madrid'},
    { title: 'Málaga'},
    { title: 'Murcia'},
    { title: 'Navarra'},
    { title: 'Ourense'},
    { title: 'Palencia'},
    { title: 'Pontevedra'},
    { title: 'Salamanca'},
    { title: 'Segovia'},
    { title: 'Sevilla'},
    { title: 'Soria'},
    { title: 'Tarragona'},
    { title: 'Santa Cruz de Tenerife'},
    { title: 'Teruel'},
    { title: 'Toledo'},
    { title: 'Valencia'},
    { title: 'Valladolid'},
    { title: 'Vizcaya'},
    { title: 'Zamora'},
    { title: 'Zaragoza'},
    { title: 'Ceuta'},
    { title: 'Melilla'},
  ];